= Minecraft: O Básico - 01

:published_at: 2017-01-30
:hp-tags: Minecraft

== O Início


Quando você cria um novo mundo, como todos sabem (eu acho ;D), a primeira coisa que se faz é pegar madeira.

No início, eu costumo e dá bem para o começo, pegar 20 madeiras brutas (tronco), 16 para madeira refinada e 4 para fazer carvão vegetal. Depois de pegar as madeiras, faça uma bancada de trabalho e 16 gravetos. Faça na bancada uma picareta de madeira e pegue 17 pedras (8-Fornalha; 3-Picareta; 3-Machado 2-Espada; 1-Pá).

Depois de fazer sua espada, saia para caçar, afinal você precisa de comida. Mate todo e qualquer animal que estiver perto de você (menos cavalo, será muito util no futuro).

Depois de pegar um pouco de comida, você irá perceber que já é quase noite (a não ser que você seja muito rápido!), então, se próximo de você tiver uma montanha, cave nela fazendo um pequeno abrigo (eu particularmente faço 3x3, gosto de coisas pequenas, eficientes e bonitas) mas se você quiser faça maior. Coloque sua fornalha e faça o carvão vegetal, e quando o primeiro ficar pronto já faça tochas e ilumine a entrada e dentro de seu abrigo. Depois que todos seus carvões ficarem prontos coloque madeira (use todos seus carvões em tochas) na fornalha e suas carnes. Se você não tiver cama (bem meu caso, tenho uma sorte de achar ovelha no começo...) passe sua noite minerando, e se conseguir, ache ferro.

Quando amanhecer, faça um balde se você tiver encontrado ferro (várias pessoas falam de quando achar ferro fazer logo uma picareta, eu não gosto de fazer isso, sempre faço um balde, afinal precisamos de comida né?!) e pegue água (se não tiver não tem problema, já explico como fazer*)

Perto do seu abrigo, faça um pequeno cercado (eu faço 5x5, dentro irá ter um espaço 3x3) e bem no centro cave um buraco e coloque a água. Em volta da água plante trigo. Como eu disse, gosto de coisas pequenas e eficientes, essa fazenda é pequena e prática!

*Se você não tiver ferro, procure a fonte de água mais proxima de você e nas terras em volta da água plante o máximo de sementes o possível. 

Durante o dia, cace mais animais se tiver próximo. Não gaste muito sua energia, ainda não temos comida o suficiente para gastar á vontade.

Também pegue o máximo de madeira o possível, se estiver com disposição, literalmente quebre seu machado pegando madeira. Sua madeira irá durar por um bom tempo a não ser que você vá construir uma casa. Logo estará de noite. Volte ao seu abrigo e passe novamente a noite a minerar.

(Dica: Sério, NUNCA cave para baixo <3)